sudo: required
language: generic
services:
  - docker
  
before_install:
 - docker build -t sutirthabagchi/docker-react -f Dockerfile.dev .
 
script: 
 - docker run -e CI=true sutirthabagchi/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  environment: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-448787191007"
  bucket_path: "docker-react"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  